name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: print files
      run: ls -la
    - name: show pwd
      run: pwd
    - name: Build
      run: xcodebuild -scheme SwiftUIMenuBar build
    - name: Run tests
      run: xcodebuild -scheme SwiftUIMenuBar test 
